config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'questions#index'
  resources :questions
  resources :question_accesses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_accesses

  def self.daily_access_by_discipline
    hash = {}
    questions_by_discipline = all.group_by(&:discipline)

    questions_by_discipline.each do |discipline, questions|
      hash[discipline] = questions.sum(&:daily_access)
    end

    hash.sort_by { |_discipline, daily_access| daily_access }.reverse.to_h
  end
end

app/models/question_access.rb
class QuestionAccess < ApplicationRecord
  belongs_to :question

  scope :group_by_question, ->(question_id) { where(question_id: question_id) }
  scope :sum_accesses, -> { sum(&:times_accessed) }

  def self.by_period(start_date, end_date)
    start_date = start_date.to_datetime.beginning_of_day if start_date
    end_date = end_date.to_datetime.end_of_day if end_date

    return where('date BETWEEN ? AND ?', start_date, end_date) if start_date && end_date

    return where('? <= date', start_date) if start_date

    return where('? >= date', end_date) if end_date

    all
  end

  def self.total_accesses_by_period(start_date, end_date)
    question_with_sum = []
    obj = {}
    question_accesses_by_period = by_period(start_date, end_date)

    question_accesses_by_period.includes(:question).collect(&:question).uniq.each do |question|
      obj = {}
      obj['question'] = question
      obj['sum'] = question_accesses_by_period.group_by_question(question.id).sum_accesses
      question_with_sum << obj
    end

    question_with_sum.sort_by { |o| o['sum'] }.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/question_accesses_controller.rb
class QuestionAccessesController < ApplicationController
  before_action :set_question_access, only: %i[show edit update destroy]

  def index
    if params[:start_date] || params[:end_date]
      @question_accesses = Kaminari.paginate_array(
        QuestionAccess.total_accesses_by_period(
          params[:start_date].to_date.strftime('%F'),
          params[:end_date].to_date.strftime('%F')
        )
      ).page(params[:page]).per(10)

      respond_to do |format|
        format.html
        format.js do
          render  file: 'question_accesses/question_accesses.js.erb',
                  layout: false
        end
      end
    else
      @question_accesses = Kaminari.paginate_array(
        QuestionAccess.total_accesses_by_period(nil, nil)
      ).page(params[:page]).per(10)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Kaminari.paginate_array(
      Question.daily_access_by_discipline.to_a
    )
                         .page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionsChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_accesses/_question_accesses.html.erb
<table class='table table-striped  table-dark table-bordered mt-5'>
  <thead>
    <tr>
      <td class="align-middle text-center font-weight-bold"><%= t('.table.question') %></td>
      <td class="align-middle text-center font-weight-bold"><%= t('.table.sum') %></td>
    </tr>
  </thead>

  <tbody>
    <% question_accesses.each do |question_with_sum| %>
      <tr>
        <td class="align-middle">
          <%= "#{question_with_sum['question'].id} - #{question_with_sum['question'].discipline} - #{question_with_sum['question'].statement}" %>
        </td>
        <td class="align-middle"><%= number_with_delimiter(question_with_sum['sum'], delimiter: ".") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate question_accesses %>

app/views/question_accesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center font-weight-bold"><%= t('.title') %></h1>

<div class='mt-5'>
  <h3><%= t('.datepicker.title') %></h3>
  <div class="input-daterange input-group">
    <input type="text" name="start_date" id="start_date"/>
    <span class="input-group-addon"> até </span>
    <input type="text" name="end_date" id="end_date"/>
  </div>

  <%= button_tag(type: 'submit', id: "sender", class: "btn btn-primary mt-2") do %>
    Buscar
  <% end %>
</div>

<div id="question_accesses">
  <%= render partial: "question_accesses",  locals: { question_accesses: @question_accesses } %>
</div>

<%= link_to t('.question'), questions_path, class: 'btn btn-secondary' %>

<br>

<script type="text/javascript">
  var questions_path = '#{questions_path}'

  $(document).ready(function(){
    $('.input-daterange').datepicker({
      format: 'dd/mm/yyyy',
      language: "pt-BR",
      forceParse: false,
      todayHighlight: true
    });

    $("#sender").click(function(){
      var start_date = $("#start_date").val();
      var end_date = $("#end_date").val();

      $.ajax({
        type: 'get',
        url: questions_path,
        dataType: 'script',
        data: { start_date: start_date, end_date: end_date },
        success: function(data){
        },
        fail: function(data) {
        },
        error: function(data) {
        }
      })

    });
  });
</script>

app/views/question_accesses/question_accesses.js.erb
$('#question_accesses').html("<%= escape_javascript(render(partial: 'question_accesses', locals: { question_accesses: @question_accesses })) %>");

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center font-weight-bold"><%= t('.title') %></h1>

<table class='table table-striped  table-dark table-bordered mt-5'>
  <thead>
    <tr>
      <td class="align-middle text-center font-weight-bold"><%= t('.table.discipline') %></td>
      <td class="align-middle text-center font-weight-bold"><%= t('.table.quantity') %></td>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |discipline, quantity| %>
      <tr>
        <td class="align-middle"><%= discipline %></td>
        <td class="align-middle"><%= number_with_delimiter(quantity, delimiter: ".") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @questions %>

<%= link_to t('.question_access'), question_accesses_path, class: 'btn btn-secondary'%>

<br>